#!/usr/bin/env bash

# Fichier de configuration des paquets PACMAN officiels
# Vous pouvez modifier ce fichier pour personnaliser les paquets officiels à installer

PACMAN_PACKAGES=(
  qt5-wayland
  qt6-wayland
  openrgb
  gnome-disk-utility
  timeshift
  firewall-config
)
