#!/usr/bin/env bash

# Applications Flatpak a installer depuis Flathub.
# Exemple: org.mozilla.firefox
FLATPAK_PACKAGES=(

    # Magasin de logiciels Flatpak
    io.github.kolunmi.Bazaar
    #org.dupot.easyflatpak
    
    # Utilitaires Flatpak
    io.github.flattool.Warehouse
    com.github.tchx84.Flatseal
    io.github.giantpinkrobots.flatsweep

    # Utilitaires audio
    com.github.wwmm.easyeffects

    # Utilitaires pour distrobox
    io.github.dvlv.boxbuddyrs.BoxBuddy

    # Utilitaire pour les appimages
    it.mijorus.gearlever.Gearlever
    
    # Utilitaire pour les applications Windows dans Bottles
    com.usebottles.bottles
)
