#!/usr/bin/env bash

# Paquets KDE/Plasma a installer avec pacman.
# Ajustez cette liste selon vos besoins avant de lancer le script.
KDE_PACKAGES=(

  yakuake
  krusader
  systemdgenie
  kio-extras
  dolphin-plugins
  print-manager
  merkuro
  isoimagewriter
  
)
