#!/usr/bin/env bash

# Paquets des depots officiels a installer avec pacman.
PACMAN_PACKAGES=(
  
  # Requis pour Niri
  qt5-wayland
  qt6-wayland
  
  # Utilitaires
  openrgb
  gnome-disk-utility
  gparted
  timeshift
  firewall-config
  qbittorrent
  transmission-qt

  # Terminal et utilitaires CLI
  kitty
  btop
  fastfetch
  lshw
  p7zip
  yazi

  # Virtualisation et conteneurs
  distrobox
  virt-manager
  qemu-full
  swtpm

  # Sécurité et confidentialité
  keepassxc
  bitwarden

  # Navigateurs web et email
  firefox-i18n-fr
  brave-bin
  vivaldi
  vivaldi-ffmpeg-codecs 
  thunderbird
  thunderbird-i18n-fr

  # Communication
  discord

  # Multimédia
  vlc
  spotify
  strawberry

  # Développement
  code
  meld
  zed
  lazygit

  # Office
  libreoffice-fresh
  libreoffice-fresh-fr
  obsidian

  # Polices
  ttf-jetbrains-mono-nerd

)
